import { ProjectManager } from './project-manager';
import { DocCategory } from '@idea-to-deploy/types';

export class AIBuilder {
    private projectManager = new ProjectManager();

    async buildProject(projectId: string, description: string): Promise<any> {
        const docs = await this.projectManager.getDocs(projectId);
        const functionalDoc = docs.find(d => d.category === 'FUNCTIONAL' as DocCategory);
        const uiuxDoc = docs.find(d => d.category === 'UI_UX' as DocCategory);
        const projects = await this.projectManager.getAllProjects();
        const project = projects.find(p => p.id === projectId);

        let features: string[] = ['Authentication', 'User Profile', 'Dashboard Settings'];
        if (functionalDoc) {
            const matches = functionalDoc.content.match(/- \*\*(.*?)\*\*/g);
            if (matches) features = matches.map(m => m.replace('- **', '').replace('**', ''));
        }

        let screens: string[] = ['Dashboard', 'Profile', 'Settings'];
        if (uiuxDoc) {
            const matches = uiuxDoc.content.match(/### (.*?) Screen/g);
            if (matches) screens = matches.map(m => m.replace('### ', '').replace(' Screen', ''));
        }

        const files: any[] = [];

        // 1. Root Configuration
        const shortName = description.toLowerCase()
            .split(' ')
            .slice(0, 3)
            .join('-')
            .replace(/[^a-z0-9-]/g, '')
            .substring(0, 30) || 'generated-project';

        files.push({
            path: 'package.json', content: JSON.stringify({
                name: shortName,
                version: '1.0.0',
                private: true,
                workspaces: ['apps/*', 'packages/*'],
                scripts: {
                    "dev": "turbo run dev",
                    "build": "turbo run build",
                    "lint": "turbo run lint",
                    "format": "prettier --write \"**/*.{ts,tsx,md}\"",
                    "dev:web": "npm run dev --workspace=web",
                    "dev:api": "npm run dev --workspace=api",
                    "db:generate": "npm run db:generate --workspace=database"
                },
                devDependencies: {
                    "turbo": "^1.12.4",
                    "prettier": "^3.2.5",
                    "typescript": "^5.3.3"
                }
            }, null, 2)
        });

        files.push({
            path: 'turbo.json',
            content: JSON.stringify({
                "$schema": "https://turbo.build/schema.json",
                "globalDependencies": ["**/.env.*local"],
                "pipeline": {
                    "build": {
                        "dependsOn": ["^build"],
                        "outputs": [".next/**", "dist/**"]
                    },
                    "lint": {},
                    "dev": {
                        "cache": false,
                        "persistent": true
                    }
                }
            }, null, 2)
        });

        files.push({
            path: 'tsconfig.json',
            content: JSON.stringify({
                "compilerOptions": {
                    "target": "ESNext",
                    "lib": ["dom", "dom.iterable", "esnext"],
                    "allowJs": true,
                    "skipLibCheck": true,
                    "strict": true,
                    "forceConsistentCasingInFileNames": true,
                    "noEmit": true,
                    "esModuleInterop": true,
                    "module": "esnext",
                    "moduleResolution": "node",
                    "resolveJsonModule": true,
                    "isolatedModules": true,
                    "jsx": "preserve",
                    "incremental": true,
                    "baseUrl": ".",
                    "paths": {
                        "@/*": ["./*"]
                    }
                },
                "exclude": ["node_modules"]
            }, null, 2)
        });

        files.push({
            path: 'README.md',
            content: `# ${description}

Automatically generated by **Idea-to-Deploy Platform**.

## Project Overview
This project is a high-performance, full-stack application scaffolding generated based on your product idea. It uses a modern monorepo structure with **Turbo**, **Next.js**, **Express**, and **Prisma**.

## Project Structure
- \`apps/web\`: Next.js 14 frontend with **Tailwind CSS**, **Lucide Icons**, and **Glassmorphism** UI components.
- \`apps/api\`: Express.js backend with **TypeScript** and modular routing.
- \`packages/database\`: Shared database layer using **Prisma ORM**.

## Getting Started

### 1. Prerequisites
- **Node.js**: v18.17.0 or higher
- **npm**: v9 or higher

### 2. Installation
Extract the zip and run the following command in the root directory:
\`\`\`bash
npm install
\`\`\`

### 3. Environment Setup
Create a \`.env\` file in the root directory (you can copy from \`.env.example\`):
\`\`\`bash
cp .env.example .env
\`\`\`
*Note: Ensure you have a PostgreSQL database running or update the \`DATABASE_URL\`.*

### 4. Running the Project
Launch both frontend and backend concurrently in development mode:
\`\`\`bash
npm run dev
\`\`\`
- Frontend: [http://localhost:3000](http://localhost:3000)
- Backend: [http://localhost:4000](http://localhost:4000)

### 5. Available Pages
Once the project is running, you can visit these specific screens:
${screens.map(s => `- **${s}**: [http://localhost:3000/${s.toLowerCase().replace(/\s+/g, '-') || ''}](http://localhost:3000/${s.toLowerCase().replace(/\s+/g, '-') || ''})`).join('\n')}

## Build for Production
To generate production bundles for all apps:
\`\`\`bash
npm run build
\`\`\`

## Deployment
Refer to \`render.yaml\` for automated deployment configuration on Render.com.
`
        });

        files.push({ path: '.env.example', content: 'DATABASE_URL="postgresql://user:pass@localhost:5432/db"\nJWT_SECRET="generate-a-secure-secret-here"\nPORT=4000' });

        // 2. Frontend (Next.js + Tailwind)
        files.push({
            path: 'apps/web/package.json',
            content: JSON.stringify({
                name: "web",
                version: "1.0.0",
                scripts: {
                    "dev": "next dev",
                    "build": "next build",
                    "start": "next start",
                    "lint": "next lint"
                },
                dependencies: {
                    "next": "14.2.22",
                    "react": "^18.2.0",
                    "react-dom": "^18.2.0",
                    "lucide-react": "^0.344.0",
                    "clsx": "^2.1.0",
                    "tailwind-merge": "^2.2.1"
                },
                devDependencies: {
                    "autoprefixer": "^10.4.17",
                    "postcss": "^8.4.35",
                    "tailwindcss": "^3.4.1",
                    "typescript": "^5.3.3",
                    "@types/node": "^20.11.20",
                    "@types/react": "^18.2.57",
                    "@types/react-dom": "^18.2.19"
                }
            }, null, 2)
        });

        files.push({
            path: 'apps/web/tailwind.config.js',
            content: `/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./app/**/*.{js,ts,tsx,jsx}",
    "./components/**/*.{js,ts,tsx,jsx}",
  ],
  theme: {
    extend: {
      colors: {
        primary: {
          50: '#f0f9ff',
          100: '#e0f2fe',
          500: '#0ea5e9',
          600: '#0284c7',
          700: '#0369a1',
        }
      },
      backgroundImage: {
        'gradient-radial': 'radial-gradient(var(--tw-gradient-stops))',
        'gradient-conic': 'conic-gradient(from 180deg at 50% 50%, var(--tw-gradient-stops))',
      },
    },
  },
  plugins: [],
}`
        });

        files.push({
            path: 'apps/web/next.config.js',
            content: `/** @type {import('next').NextConfig} */
const nextConfig = {
  reactStrictMode: true,
  swcMinify: true,
}
module.exports = nextConfig`
        });

        files.push({
            path: 'apps/web/postcss.config.js',
            content: `module.exports = {
  plugins: {
    tailwindcss: {},
    autoprefixer: {},
  },
}`
        });

        files.push({
            path: 'apps/web/app/globals.css',
            content: `@tailwind base;
@tailwind components;
@tailwind utilities;

:root {
  --foreground-rgb: 15, 23, 42;
  --background-start-rgb: 248, 250, 252;
  --background-end-rgb: 255, 255, 255;
}

body {
  color: rgb(var(--foreground-rgb));
  background: linear-gradient(
      to bottom,
      transparent,
      rgb(var(--background-end-rgb))
    )
    rgb(var(--background-start-rgb));
  min-height: 100vh;
}

.glass-card {
  background: rgba(255, 255, 255, 0.7);
  backdrop-filter: blur(12px);
  -webkit-backdrop-filter: blur(12px);
  border: 1px solid rgba(255, 255, 255, 0.3);
  box-shadow: 0 8px 32px 0 rgba(31, 38, 135, 0.07);
}
`
        });

        files.push({
            path: 'apps/web/tsconfig.json',
            content: JSON.stringify({
                "compilerOptions": {
                    "target": "ESNext",
                    "lib": ["dom", "dom.iterable", "esnext"],
                    "allowJs": true,
                    "skipLibCheck": true,
                    "strict": true,
                    "forceConsistentCasingInFileNames": true,
                    "noEmit": true,
                    "esModuleInterop": true,
                    "module": "esnext",
                    "moduleResolution": "node",
                    "resolveJsonModule": true,
                    "isolatedModules": true,
                    "jsx": "preserve",
                    "incremental": true,
                    "plugins": [
                        {
                            "name": "next"
                        }
                    ],
                    "paths": {
                        "@/*": ["./*"]
                    }
                },
                "include": ["next-env.d.ts", "**/*.ts", "**/*.tsx", ".next/types/**/*.ts"],
                "exclude": ["node_modules"]
            }, null, 2)
        });

        files.push({
            path: 'apps/web/next-env.d.ts',
            content: '/// <reference types="next" />\n/// <reference types="next/navigation-types/navigation" />\n'
        });

        files.push({
            path: 'apps/web/app/layout.tsx',
            content: `
import './globals.css';
import { Inter } from 'next/font/google';

const inter = Inter({ subsets: ['latin'] });

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  );
}
`
        });

        // Generate Sophisticated Pages
        screens.forEach(screen => {
            const slug = screen.toLowerCase().replace(/\s+/g, '-');
            const sectionRegex = new RegExp(`### ${screen} Screen([\\s\\S]*?)(?=###|$)`, 'i');
            const section = uiuxDoc?.content.match(sectionRegex)?.[1] || '';
            const screenComponents = section.match(/- \*\*Components\*\*: (.*)/)?.[1]?.split(',').map(c => c.trim()) || [];
            const screenPurpose = section.match(/- \*\*Purpose\*\*: (.*)/)?.[1] || 'Main interface for ' + screen;
            const interactions = section.match(/- \*\*Interactions\*\*: (.*)/)?.[1] || 'Standard user interactions';

            files.push({
                path: `apps/web/app/${slug === 'dashboard' ? '' : slug}/page.tsx`,
                content: `
import React from 'react';
import { 
  Activity, Layout, Shield, Users, CheckCircle, 
  ArrowRight, Search, Bell, Settings, Menu,
  CreditCard, PieChart, Zap, Layers, Cpu
} from 'lucide-react';

export default function ${screen.replace(/\s+/g, '')}Page() {
  const screens = ${JSON.stringify(screens.slice(0, 4))};
  const screenComponents = ${JSON.stringify(screenComponents)};
  const features = ${JSON.stringify(features.slice(0, 5))};

  return (
    <div className="min-h-screen bg-slate-50 text-slate-900">
      {/* Navigation Bar */}
      <nav className="sticky top-0 z-50 glass-card border-b border-slate-200 px-6 py-4">
        <div className="max-w-7xl mx-auto flex items-center justify-between">
          <div className="flex items-center gap-2">
            <div className="w-10 h-10 bg-indigo-600 rounded-xl flex items-center justify-center text-white shadow-lg shadow-indigo-200">
              <Zap className="w-6 h-6" />
            </div>
            <span className="text-xl font-bold tracking-tight">${description.split(' ')[0]}</span>
          </div>
          <div className="hidden md:flex items-center gap-8 text-sm font-medium text-slate-600">
            {screens.map(s => (
              <a key={s} href={\`/\${s.toLowerCase().replace(/\\s+/g, '-')}\`} className="hover:text-indigo-600 transition-colors">{s}</a>
            ))}
          </div>
          <div className="flex items-center gap-4">
            <button className="p-2 text-slate-400 hover:text-slate-600 transition-colors">
              <Bell className="w-5 h-5" />
            </button>
            <div className="w-8 h-8 rounded-full bg-gradient-to-tr from-indigo-500 to-purple-500 border-2 border-white shadow-sm"></div>
          </div>
        </div>
      </nav>

      <main className="max-w-7xl mx-auto px-6 py-12">
        <header className="mb-12">
          <div className="flex items-center gap-3 mb-4">
            <span className="px-3 py-1 bg-indigo-100 text-indigo-700 text-[11px] font-bold uppercase tracking-wider rounded-full">
              Phase: Design to Code
            </span>
          </div>
          <h1 className="text-5xl font-black tracking-tight text-slate-900 mb-6 bg-clip-text text-transparent bg-gradient-to-r from-slate-900 to-indigo-700">
            ${screen}
          </h1>
          <p className="text-xl text-slate-500 max-w-3xl leading-relaxed">
            ${screenPurpose}
          </p>
        </header>

        <div className="grid lg:grid-cols-3 gap-10">
          <div className="lg:col-span-2 space-y-10">
            {/* Component Grid */}
            <div className="grid md:grid-cols-2 gap-6">
              {screenComponents.map((comp, idx) => (
                <section key={idx} className="glass-card p-8 rounded-3xl group hover:shadow-2xl hover:shadow-indigo-100/50 transition-all duration-500 hover:-translate-y-1 border border-slate-200/60">
                  <div className="flex items-start justify-between mb-6">
                    <div className="w-12 h-12 bg-slate-100 rounded-2xl flex items-center justify-center group-hover:bg-indigo-600 group-hover:text-white transition-colors duration-500">
                      {idx % 2 === 0 ? <Layers className="w-6 h-6" /> : <Cpu className="w-6 h-6" />}
                    </div>
                    <span className="text-[10px] font-bold uppercase tracking-widest text-slate-400">Component</span>
                  </div>
                  <h3 className="text-2xl font-extrabold mb-3 text-slate-800">
                    {comp}
                  </h3>
                  <p className="text-slate-500 text-sm mb-6 leading-relaxed">
                    High-performance {comp} module integrated with the core ${description} engine.
                  </p>
                  <div className="h-40 bg-slate-50/50 rounded-2xl border border-dashed border-slate-200 flex flex-col items-center justify-center relative overflow-hidden group-hover:border-indigo-200 transition-colors">
                    <div className="absolute inset-0 bg-gradient-to-br from-indigo-50/20 to-transparent group-hover:opacity-100 opacity-0 transition-opacity"></div>
                    <Activity className="w-8 h-8 text-slate-300 mb-2 group-hover:text-indigo-400 group-hover:animate-pulse transition-colors" />
                    <p className="text-xs font-semibold text-slate-400 group-hover:text-indigo-600 transition-colors tracking-wide">
                      Live Rendering Preview
                    </p>
                  </div>
                </section>
              ))}
            </div>
            
            <section className="bg-slate-900 rounded-[2.5rem] p-10 text-white shadow-2xl relative overflow-hidden">
                <div className="absolute top-0 right-0 w-64 h-64 bg-indigo-500/10 blur-[100px] -mr-32 -mt-32"></div>
                <div className="relative z-10">
                    <h3 className="text-3xl font-bold mb-4 flex items-center gap-3">
                        <Shield className="w-8 h-8 text-indigo-400" />
                        Infrastructure & Logic
                    </h3>
                    <p className="text-slate-400 text-lg mb-8 max-w-xl">
                        Integrated workflows: ${interactions}
                    </p>
                    <div className="grid grid-cols-2 md:grid-cols-4 gap-6">
                        {[1, 2, 3, 4].map(i => (
                            <div key={i} className="p-4 bg-white/5 rounded-2xl border border-white/10">
                                <p className="text-[10px] font-bold text-indigo-400 uppercase mb-1">Node 0{i}</p>
                                <p className="text-sm font-bold">Active</p>
                            </div>
                        ))}
                    </div>
                </div>
            </section>
          </div>

          <div className="space-y-8">
            <div className="glass-card p-10 rounded-[2.5rem] border border-slate-200/60 shadow-xl shadow-slate-200/50">
              <h4 className="text-sm font-black uppercase tracking-[0.2em] text-indigo-600 mb-8 flex items-center gap-2">
                <PieChart className="w-4 h-4" />
                Performance Metrics
              </h4>
              <div className="space-y-8">
                <div>
                  <div className="flex justify-between text-sm font-bold mb-2">
                    <span className="text-slate-500 uppercase tracking-wider">Complexity</span>
                    <span className="text-indigo-600">High</span>
                  </div>
                  <div className="w-full h-2 bg-slate-100 rounded-full overflow-hidden">
                    <div className="w-[85%] h-full bg-indigo-600 rounded-full"></div>
                  </div>
                </div>
                <div>
                  <div className="flex justify-between text-sm font-bold mb-2">
                    <span className="text-slate-500 uppercase tracking-wider">Load Speed</span>
                    <span className="text-emerald-500">Optimal</span>
                  </div>
                  <div className="w-full h-2 bg-slate-100 rounded-full overflow-hidden">
                    <div className="w-[98%] h-full bg-emerald-500 rounded-full"></div>
                  </div>
                </div>
              </div>
              
              <div className="mt-12 p-6 bg-slate-50 rounded-2xl border border-slate-100">
                <h5 className="text-xs font-bold text-slate-400 uppercase tracking-widest mb-4">Core Functions</h5>
                <ul className="space-y-3">
                  {features.map(f => (
                    <li key={f} className="flex items-center gap-2 text-sm font-semibold text-slate-600">
                      <CheckCircle className="w-4 h-4 text-indigo-500" />
                      {f}
                    </li>
                  ))}
                </ul>
              </div>
            </div>

            <div className="bg-indigo-600 p-8 rounded-[2.5rem] text-white shadow-lg shadow-indigo-200 group cursor-pointer overflow-hidden relative">
                <div className="absolute inset-0 bg-gradient-to-br from-indigo-400 to-indigo-700 opacity-0 group-hover:opacity-100 transition-opacity"></div>
                <div className="relative z-10">
                    <h4 className="text-xl font-bold mb-2">Export Code</h4>
                    <p className="text-indigo-100 text-sm mb-6">Ready for production deployment</p>
                    <div className="w-12 h-12 bg-white/20 rounded-xl flex items-center justify-center group-hover:scale-110 transition-transform">
                        <ArrowRight className="w-6 h-6" />
                    </div>
                </div>
            </div>
          </div>
        </div>
      </main>
    </div>
  );
}
`
            });
        });

        // 3. Backend (Express + TypeScript)
        files.push({
            path: 'apps/api/package.json',
            content: JSON.stringify({
                name: "api",
                version: "1.0.0",
                scripts: {
                    "dev": "tsx watch src/index.ts",
                    "build": "tsc",
                    "start": "node dist/index.js"
                },
                dependencies: {
                    "express": "^4.18.2",
                    "cors": "^2.8.5",
                    "dotenv": "^16.4.5",
                    "zod": "^3.22.4"
                },
                devDependencies: {
                    "typescript": "^5.3.3",
                    "tsx": "^4.7.1",
                    "@types/express": "^4.17.21",
                    "@types/cors": "^2.8.17",
                    "@types/node": "^20.11.20"
                }
            }, null, 2)
        });

        files.push({
            path: 'apps/api/tsconfig.json',
            content: JSON.stringify({
                "compilerOptions": {
                    "target": "ESNext",
                    "module": "commonjs",
                    "outDir": "./dist",
                    "rootDir": "./src",
                    "strict": true,
                    "esModuleInterop": true,
                    "skipLibCheck": true,
                    "forceConsistentCasingInFileNames": true
                },
                "include": ["src/**/*"]
            }, null, 2)
        });

        files.push({
            path: 'apps/api/src/index.ts', content: `
import express from 'express';
import cors from 'cors';
import dotenv from 'dotenv';
import { featureRouter } from './routes/features';

dotenv.config();

const app = express();
const PORT = process.env.PORT || 4000;

app.use(cors());
app.use(express.json());

app.get('/health', (req, res) => res.json({ status: 'ok', timestamp: new Date() }));
app.use('/api', featureRouter);

app.listen(PORT, () => {
    console.log(\`🚀 API Server running at http://localhost:\${PORT}\`);
});
` });

        files.push({
            path: 'apps/api/src/routes/features.ts', content: `
import { Router } from 'express';
export const featureRouter = Router();

${features.map(f => `
// ${f} endpoint
featureRouter.get('/${f.toLowerCase().replace(/\s+/g, '-')}', (req, res) => {
    res.json({ 
        success: true,
        project: '${description}',
        feature: '${f}',
        data: {
            id: Math.random().toString(36).substr(2, 9),
            status: 'active',
            lastUpdated: new Date()
        }
    });
});
`).join('\n')}
` });

        // 4. Database (Prisma)
        files.push({
            path: 'packages/database/package.json',
            content: JSON.stringify({
                name: "database",
                version: "1.0.0",
                scripts: {
                    "dev": "npm run db:generate",
                    "build": "npm run db:generate",
                    "db:generate": "prisma generate",
                    "db:push": "prisma db push"
                },
                dependencies: {
                    "@prisma/client": "^5.10.2"
                },
                devDependencies: {
                    "prisma": "^5.10.2"
                }
            }, null, 2)
        });

        files.push({
            path: 'packages/database/tsconfig.json',
            content: JSON.stringify({
                "compilerOptions": {
                    "target": "ESNext",
                    "module": "commonjs",
                    "strict": true,
                    "esModuleInterop": true,
                    "skipLibCheck": true,
                    "forceConsistentCasingInFileNames": true
                }
            }, null, 2)
        });

        files.push({
            path: 'packages/database/prisma/schema.prisma', content: `
generator client {
  provider = "prisma-client-js"
}

datasource db {
  provider = "postgresql"
  url      = env("DATABASE_URL")
}

model User {
  id        String   @id @default(uuid())
  email     String   @unique
  name      String?
  projects  Project[]
  createdAt DateTime @default(now())
}

model Project {
  id          String   @id @default(uuid())
  title       String
  description String
  userId      String
  user        User     @relation(fields: [userId], references: [id])
  createdAt   DateTime @default(now())
}

${features.filter(f => !['Login', 'Logout', 'Registration'].includes(f)).map(f => `
model ${f.replace(/\s+/g, '')} {
  id        String   @id @default(uuid())
  details   Json
  status    String   @default("pending")
  createdAt DateTime @default(now())
}
`).join('\n')}
` });

        return {
            status: 'success',
            files,
            projectId,
            metadata: {
                totalFiles: files.length,
                generatedAt: new Date().toISOString(),
                frameworks: ['Next.js 14', 'Express', 'Prisma', 'Tailwind CSS']
            },
            pipeline: [
                { step: 'Analysis Verification', status: 'done' },
                { step: 'Scaffolding Premium UI/UX', status: 'done' },
                { step: 'Generating Frontend Pages', status: 'done' },
                { step: 'Generating API Controllers', status: 'done' },
                { step: 'Defining DB Schema', status: 'done' },
                { step: 'Writing Documentation', status: 'done' },
                { step: 'Finalizing Bundle', status: 'done' }
            ]
        };
    }
}
