from fastapi import FastAPI
from fastapi.middleware.cors import CORSMiddleware
from database import engine, Base
try:
    from auth_routes import router as auth_router
except ImportError:
    auth_router = None
from routes.user_routes import router as user_router
from routes.dashboard_routes import router as dashboard_router

# Create database tables
if engine:
    Base.metadata.create_all(bind=engine)

app = FastAPI(
    title="Build a customer support platform that allows user... API",
    description="Generated by Idea-to-Deploy",
    version="1.0.0"
)

# CORS middleware
app.add_middleware(
    CORSMiddleware,
    allow_origins=["http://localhost:3000"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

# Include routers
if auth_router:
    app.include_router(auth_router)

app.include_router(user_router)
app.include_router(dashboard_router)

@app.get("/")
async def root():
    return {"message": "Welcome to Build a customer support platform that allows user... API"}

@app.get("/health")
async def health():
    return {"status": "healthy"}
