from fastapi import FastAPI
from fastapi.middleware.cors import CORSMiddleware
from database import engine, Base
try:
    from auth_routes import router as auth_router
except ImportError:
    auth_router = None
from routes.landing_routes import router as landing_router
from routes.home_routes import router as home_router
from routes.friend_routes import router as friend_router
from routes.user_routes import router as user_router
from routes.account_routes import router as account_router
from routes.alert_routes import router as alert_router

# Create database tables
if engine:
    Base.metadata.create_all(bind=engine)

app = FastAPI(
    title="CREATE A SOCIAL MEDIA PLATFORM
 API",
    description="Generated by Idea-to-Deploy",
    version="1.0.0"
)

# CORS middleware
app.add_middleware(
    CORSMiddleware,
    allow_origins=["http://localhost:3000"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

# Include routers
if auth_router:
    app.include_router(auth_router)

app.include_router(landing_router)
app.include_router(home_router)
app.include_router(friend_router)
app.include_router(user_router)
app.include_router(account_router)
app.include_router(alert_router)

@app.get("/")
async def root():
    return {"message": "Welcome to CREATE A SOCIAL MEDIA PLATFORM
 API"}

@app.get("/health")
async def health():
    return {"status": "healthy"}
