import json
import re
from typing import Dict, Any, List
from .project_manager import ProjectManager, ARTIFACTS_DIR
from .llm_service import LLMService
from .ai_prompts import PAGE_CODE_PROMPT

class AIBuilder:
    def __init__(self):
        self.project_manager = ProjectManager()
        self.llm = LLMService()

    def _clean_code(self, raw: str) -> str:
        """Strip markdown code blocks"""
        code = raw.strip()
        if code.startswith('```'):
            parts = code.split('\n', 1)
            if len(parts) > 1:
                code = parts[1]
        if code.endswith('```'):
            code = code.rsplit('\n', 1)[0]
        # Remove language identifier if present
        if code.startswith('tsx') or code.startswith('typescript') or code.startswith('javascript'):
             code = code.split('\n', 1)[1]
        return code

    async def build_project(self, project_id: str, description: str) -> Dict[str, Any]:
        docs = await self.project_manager.get_docs(project_id)
        
        # Find Functional and UI/UX docs
        functional_doc = next((d for d in docs if d.category == 'REQUIREMENTS'), None)
        uiux_doc = next((d for d in docs if d.category == 'UI_UX'), None)
        
        # Extract features
        features = ['Authentication', 'User Profile', 'Dashboard Settings']
        if functional_doc:
            matches = re.findall(r'- \*\*(.*?)\*\*', functional_doc.content)
            if matches:
                features = [m.replace('- **', '').replace('**', '') for m in matches]

        # Extract screens (Fallback list)
        screens = ['Dashboard', 'Profile', 'Settings']
        if uiux_doc:
            matches = re.findall(r'### (.*?) Screen', uiux_doc.content)
            if matches:
                screens = [m.replace('### ', '').replace(' Screen', '') for m in matches]
        
        # Ensure Auth screens exist in basic list
        if 'Login' not in screens: screens.append('Login')
        if 'Register' not in screens: screens.append('Register')

        files = []

        # 1. Root Configuration
        short_name = description.lower().split(' ')[:3]
        short_name = '-'.join(short_name)
        short_name = re.sub(r'[^a-z0-9-]', '', short_name)[:30] or 'generated-project'

        files.append({
            "path": "package.json",
            "content": json.dumps({
                "name": short_name,
                "version": "1.0.0",
                "private": True,
                "workspaces": ["apps/*"],
                "scripts": {
                    "dev": "turbo run dev",
                    "build": "turbo run build",
                    "lint": "turbo run lint",
                    "format": "prettier --write \"**/*.{ts,tsx,md}\"",
                    "dev:web": "npm run dev --workspace=web",
                    "dev:api": "npm run dev --workspace=api"
                },
                "devDependencies": {
                    "turbo": "^1.12.4",
                    "prettier": "^3.2.5",
                    "typescript": "^5.3.3"
                }
            }, indent=2)
        })

        files.append({
            "path": "turbo.json",
            "content": json.dumps({
                "$schema": "https://turbo.build/schema.json",
                "globalDependencies": ["**/.env.*local"],
                "pipeline": {
                    "build": {
                        "dependsOn": ["^build"],
                        "outputs": [".next/**", "dist/**"]
                    },
                    "lint": {},
                    "dev": {
                        "cache": False,
                        "persistent": True
                    }
                }
            }, indent=2)
        })

        files.append({
            "path": "tsconfig.json",
            "content": json.dumps({
                "compilerOptions": {
                    "target": "ESNext",
                    "lib": ["dom", "dom.iterable", "esnext"],
                    "allowJs": True,
                    "skipLibCheck": True,
                    "strict": True,
                    "forceConsistentCasingInFileNames": True,
                    "noEmit": True,
                    "esModuleInterop": True,
                    "module": "esnext",
                    "moduleResolution": "node",
                    "resolveJsonModule": True,
                    "isolatedModules": True,
                    "jsx": "preserve",
                    "incremental": True,
                    "baseUrl": ".",
                    "paths": {
                        "@/*": ["./*"]
                    }
                },
                "exclude": ["node_modules"]
            }, indent=2)
        })
        
        # README (Placeholder, updated later?)
        readme_content = f"""# {description}
Automatically generated by **Idea-to-Deploy Platform**.
...
"""
        files.append({
            "path": "README.md",
            "content": readme_content
        })
        
        files.append({ "path": ".env.example", "content": 'DATABASE_URL="postgresql://user:pass@localhost:5432/db"\nJWT_SECRET="generate-a-secure-secret-here"\nPORT=4000' })

        # 2. Frontend (Next.js + Tailwind)
        files.append({
            "path": "apps/web/package.json",
            "content": json.dumps({
                "name": "web",
                "version": "1.0.0",
                "scripts": {
                    "dev": "next dev",
                    "build": "next build",
                    "start": "next start",
                    "lint": "next lint"
                },
                "dependencies": {
                    "next": "14.2.22",
                    "react": "^18.2.0",
                    "react-dom": "^18.2.0",
                    "lucide-react": "^0.344.0",
                    "clsx": "^2.1.0",
                    "tailwind-merge": "^2.2.1"
                },
                "devDependencies": {
                    "autoprefixer": "^10.4.17",
                    "postcss": "^8.4.35",
                    "tailwindcss": "^3.4.1",
                    "typescript": "^5.3.3",
                    "@types/node": "^20.11.20",
                    "@types/react": "^18.2.57",
                    "@types/react-dom": "^18.2.19"
                }
            }, indent=2)
        })
        
        files.append({
            "path": "apps/web/tailwind.config.js",
            "content": """/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./app/**/*.{js,ts,tsx,jsx}",
    "./components/**/*.{js,ts,tsx,jsx}",
  ],
  theme: {
    extend: {
      colors: {
        primary: { 50: '#f0f9ff', 500: '#0ea5e9', 600: '#0284c7' }
      }
    },
  },
  plugins: [],
}"""
        })
        
        files.append({
            "path": "apps/web/next.config.js",
            "content": "/** @type {import('next').NextConfig} */\nconst nextConfig = { reactStrictMode: true }\nmodule.exports = nextConfig"
        })
        
        files.append({
            "path": "apps/web/postcss.config.js",
            "content": "module.exports = { plugins: { tailwindcss: {}, autoprefixer: {} } }"
        })
        
        files.append({
            "path": "apps/web/app/globals.css",
            "content": """@tailwind base;
@tailwind components;
@tailwind utilities;

:root {
  --foreground-rgb: 15, 23, 42;
  --background-start-rgb: 248, 250, 252;
  --background-end-rgb: 255, 255, 255;
}

body {
  color: rgb(var(--foreground-rgb));
  background: linear-gradient(to bottom, transparent, rgb(var(--background-end-rgb))) rgb(var(--background-start-rgb));
  min-height: 100vh;
}

.glass-card {
  background: rgba(255, 255, 255, 0.7);
  backdrop-filter: blur(12px);
  border: 1px solid rgba(255, 255, 255, 0.3);
  box-shadow: 0 8px 32px 0 rgba(31, 38, 135, 0.07);
}
"""
        })
        
        files.append({
            "path": "apps/web/tsconfig.json",
            "content": json.dumps({
                "compilerOptions": {
                    "target": "ESNext",
                    "lib": ["dom", "dom.iterable", "esnext"],
                    "allowJs": True,
                    "skipLibCheck": True,
                    "strict": True,
                    "noEmit": True,
                    "esModuleInterop": True,
                    "module": "esnext",
                    "moduleResolution": "node",
                    "resolveJsonModule": True,
                    "isolatedModules": True,
                    "jsx": "preserve",
                    "incremental": True,
                    "plugins": [{"name": "next"}],
                    "paths": { "@/*": ["./*"] }
                },
                "include": ["next-env.d.ts", "**/*.ts", "**/*.tsx", ".next/types/**/*.ts"],
                "exclude": ["node_modules"]
            }, indent=2)
        })
        
        files.append({
            "path": "apps/web/next-env.d.ts",
            "content": '/// <reference types="next" />\\n/// <reference types="next/navigation-types/navigation" />\\n'
        })
        
        files.append({
            "path": "apps/web/app/layout.tsx",
            "content": """
import './globals.css';
import { Inter } from 'next/font/google';
import { AuthProvider } from '../context/AuthContext';

const inter = Inter({ subsets: ['latin'] });

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AuthProvider>
            {children}
        </AuthProvider>
      </body>
    </html>
  );
}
"""
        })

        # Auth Utils
        files.append({
            "path": "apps/web/context/AuthContext.tsx", 
            "content": """
'use client';
import React, { createContext, useContext, useState, useEffect } from 'react';
import { useRouter, usePathname } from 'next/navigation';

interface User { id: number; email: string; name: string; }
interface AuthContextType { user: User | null; login: (token: string) => void; logout: () => void; isLoading: boolean; }

const AuthContext = createContext<AuthContextType>({ user: null, login: () => {}, logout: () => {}, isLoading: true });
export const useAuth = () => useContext(AuthContext);

export const AuthProvider = ({ children }: { children: React.ReactNode }) => {
    const [user, setUser] = useState<User | null>(null);
    const [isLoading, setIsLoading] = useState(true);
    const router = useRouter();
    const pathname = usePathname();

    useEffect(() => {
        const token = localStorage.getItem('token');
        if (token) {
            fetch('http://localhost:4000/auth/me', { headers: { 'Authorization': `Bearer ${token}` } })
            .then(res => res.ok ? res.json() : null)
            .then(userData => { if (userData) setUser(userData); else logout(); })
            .catch(() => logout())
            .finally(() => setIsLoading(false));
        } else { setIsLoading(false); }
    }, []);

    const login = (token: string) => {
        localStorage.setItem('token', token);
        fetch('http://localhost:4000/auth/me', { headers: { 'Authorization': `Bearer ${token}` } })
        .then(res => res.json())
        .then(userData => { setUser(userData); router.push('/dashboard'); });
    };

    const logout = () => { localStorage.removeItem('token'); setUser(null); router.push('/login'); };

    useEffect(() => {
        if (!isLoading) {
            const publicRoutes = ['/', '/login', '/register'];
            if (!user && !publicRoutes.includes(pathname)) { router.push('/login'); }
            if (user && (pathname === '/login' || pathname === '/register')) { router.push('/dashboard'); }
        }
    }, [user, isLoading, pathname]);

    return ( <AuthContext.Provider value={{ user, login, logout, isLoading }}> {children} </AuthContext.Provider> );
};
"""
        })

        # --- DYNAMIC UI GENERATION ENGINE ---

        # 1. Inject Reusable Component Library (Using @ alias in fallback)
        files.append({
            "path": "apps/web/components/UIComponents.tsx",
            "content": """
import React from 'react';
import { ArrowRight, CheckCircle, Star, Shield, Zap, Menu, Bell, Settings, User, LogOut, Layout, PieChart } from 'lucide-react';
import { useAuth } from '../context/AuthContext';

// Base Components
export const Button = ({ children, variant = 'primary', className = '', ...props }: any) => {
  const base = "px-6 py-3 rounded-xl font-bold transition-all duration-200 flex items-center justify-center gap-2 active:scale-95";
  const variants = {
    primary: "bg-indigo-600 text-white hover:bg-indigo-700 shadow-lg shadow-indigo-200",
    secondary: "bg-white text-slate-700 border border-slate-200 hover:bg-slate-50 hover:border-slate-300",
    neutral: "bg-slate-100 text-slate-900 border border-slate-200 hover:bg-slate-200",
    outline: "border-2 border-indigo-600 text-indigo-600 hover:bg-indigo-50",
    ghost: "text-slate-600 hover:bg-slate-100"
  };
  return <button className={`${base} ${variants[variant] || variants.primary} ${className}`} {...props}>{children}</button>;
};

export const Input = ({ label, subtext, ...props }: any) => (
  <div className="mb-4">
    {label && <label className="block text-sm font-bold text-slate-700 mb-1">{label}</label>}
    <input className="w-full px-4 py-3 bg-slate-50 border border-slate-200 rounded-xl focus:ring-2 focus:ring-indigo-600 focus:border-transparent outline-none transition-all" {...props} />
    {subtext && <p className="text-xs text-slate-400 mt-1">{subtext}</p>}
  </div>
);

// Sections
export const Header = ({ label }: any) => (
    <nav className="sticky top-0 z-50 glass-card border-b border-slate-200 px-6 py-4 mb-8">
        <div className="max-w-7xl mx-auto flex items-center justify-between">
            <div className="flex items-center gap-2 text-indigo-600 font-black text-xl tracking-tight">
                <div className="w-10 h-10 bg-indigo-600 text-white rounded-xl flex items-center justify-center"><Zap className="w-6 h-6" /></div>
                {label}
            </div>
            <div className="flex items-center gap-4">
                 <Button variant="ghost" className="!p-2"><Bell className="w-5 h-5" /></Button>
            </div>
        </div>
    </nav>
);

export const Hero = ({ label, content, subtext }: any) => (
    <section className="text-center py-20 px-4">
        <div className="inline-flex items-center gap-2 px-3 py-1 rounded-full bg-indigo-50 text-indigo-600 text-xs font-bold uppercase tracking-wider mb-6">{label}</div>
        <h1 className="text-5xl md:text-7xl font-black text-slate-900 mb-6 tracking-tight tight-leading max-w-4xl mx-auto">{content}</h1>
        <p className="text-xl text-slate-500 max-w-2xl mx-auto mb-10 leading-relaxed">{subtext}</p>
        <div className="flex justify-center gap-4">
            <Button>{subtext} <ArrowRight className="w-4 h-4" /></Button>
            <Button variant="secondary">Learn More</Button>
        </div>
    </section>
);

export const AuthCard = ({ label }: any) => {
    const { login } = useAuth();
    return (
        <div className="max-w-md mx-auto bg-white p-8 rounded-3xl shadow-xl border border-slate-100 my-20">
            <h2 className="text-3xl font-bold text-center mb-2">{label}</h2>
             <p className="text-slate-500 text-center mb-8">Enter your credentials to access account</p>
             <div className="space-y-4">
                <Input label="Email Address" placeholder="you@example.com" />
                <Input label="Password" type="password" placeholder="••••••••" />
                <Button className="w-full" onClick={() => login('token')}>Continue <ArrowRight className="w-4 h-4" /></Button>
             </div>
        </div>
    );
};

export const Sidebar = ({ label }: any) => (
    <div className="hidden lg:flex flex-col w-64 fixed left-0 top-0 bottom-0 bg-slate-900 text-white p-6">
        <div className="text-2xl font-bold mb-10 flex items-center gap-3"><Layout className="w-8 h-8 text-indigo-500" /> {label}</div>
        <div className="space-y-2 flex-1">
             <Button variant="ghost" className="w-full justify-start text-slate-400 hover:text-white hover:bg-white/10"><PieChart className="w-5 h-5" /> Dashboard</Button>
             <Button variant="ghost" className="w-full justify-start text-slate-400 hover:text-white hover:bg-white/10"><Settings className="w-5 h-5" /> Settings</Button>
        </div>
        <Button variant="ghost" className="w-full justify-start text-red-400 hover:bg-red-900/20"><LogOut className="w-5 h-5" /> Logout</Button>
    </div>
);

export const Footer = ({ label }: any) => (
    <footer className="bg-slate-900 text-slate-400 py-12 px-6 text-center">
        <div className="border-t border-slate-800 pt-8 text-sm">© 2024 Idea-to-Deploy. All rights reserved.</div>
    </footer>
);
"""
        })
        
        # 2. Dynamic Component & Page Builder
        wireframes_path = ARTIFACTS_DIR / project_id / "docs" / "wireframes.json"
        
        design_specs = {}
        if wireframes_path.exists():
             try:
                 with open(wireframes_path, 'r', encoding='utf-8') as f:
                     wf_data = json.loads(f.read())
                     for wf in wf_data.get('wireframes', []):
                         key = wf.get('screenKey') or wf.get('screen', '').lower().replace(' ', '')
                         design_specs[key.lower()] = wf
             except: pass
        
        defined_screens = list(design_specs.keys())
        normalized_screens = list(set([s.lower().replace(' ', '') for s in screens] + defined_screens))
        
        # Fallback Generator
        def generate_dynamic_page_fallback(screen_name, screen_key, layout_data=None):
            if not layout_data:
                if 'login' in screen_key or 'register' in screen_key:
                    layout_data = [{'components': [{'type': 'AuthCard', 'label': screen_name}]}]
                elif 'dashboard' in screen_key:
                     layout_data = [{'components': [{'type': 'Sidebar', 'label': 'App'}]}, {'components': [{'type': 'Header', 'label': screen_name}]}]
                else:
                    layout_data = [{'components': [{'type': 'Hero', 'label': screen_name, 'content': screen_name}]}]
            
            ui_imports = set()
            jsx_elements = []
            for section in layout_data:
                comps = section.get('components', [])
                for comp in comps:
                    c_type = comp.get('type', 'Hero')
                    # Basic props handling (simplified)
                    ui_imports.add(c_type)
                    jsx_elements.append(f'<{c_type} label="{comp.get("label", screen_name)}" />')

            # FIX: Use @ alias for robust import
            import_lines = f"import {{ {', '.join(ui_imports)} }} from '@/components/UIComponents';"
            wrapper_class = "min-h-screen bg-slate-50"
            if 'Sidebar' in ui_imports: wrapper_class += " lg:pl-64"
                
            return f"""
'use client';
import React from 'react';
{import_lines}

export default function {screen_key.capitalize()}Page() {{
  return (
    <div className="{wrapper_class}">
      {chr(10).join(jsx_elements)}
    </div>
  );
}}
"""
        
        generated_slugs = []
        
        # Generate Pages List
        for screen_key in normalized_screens:
            is_root = False
            slug = screen_key
            if 'dashboard' in screen_key or 'home' in screen_key or 'landing' in screen_key:
                 if 'dashboard' in screen_key: is_root = True 
            
            layout = design_specs.get(screen_key, {}).get('layout', [])
            
            # --- TRY LLM GENERATION ---
            print(f"Generating code for {screen_key}...")
            content = ""
            try:
                wf_layout_str = json.dumps(design_specs.get(screen_key, {}), indent=2)
                raw = await self.llm.generate_content('PAGE_CODE', {
                    "idea": description,
                    "screen_name": screen_key,
                    "wireframe": wf_layout_str
                }, PAGE_CODE_PROMPT)
                content = self._clean_code(raw)
            except Exception as e:
                print(f"LLM Generation failed for {screen_key}: {e}")
            
            # --- FALLBACK ---
            if not content or "import" not in content or "export default" not in content:
                print(f"Using fallback for {screen_key}")
                content = generate_dynamic_page_fallback(screen_key, screen_key, layout)
            
            # Determine Path
            path_slug = '' if is_root else screen_key
            if path_slug == 'dashboard': path_slug = ''
            if path_slug == '' and any(s == '' for s in generated_slugs): path_slug = 'dashboard' # collision resolution
            
            if path_slug == '': path = "apps/web/app/page.tsx"
            else: path = f"apps/web/app/{path_slug}/page.tsx"
            
            files.append({ "path": path, "content": content })
            generated_slugs.append(path_slug)
            
        if '' not in generated_slugs:
             files.append({ "path": "apps/web/app/page.tsx", "content": generate_dynamic_page_fallback("Home", "home") })

        # 3. Backend (Simple Keep)
        files.append({
            "path": "apps/api/package.json",
            "content": json.dumps({ "name": "api", "version": "1.0.0", "scripts": { "dev": "uvicorn main:app --reload --port 4000", "start": "uvicorn main:app --port 4000" } }, indent=2)
        })
        files.append({ "path": "apps/api/requirements.txt", "content": "fastapi==0.109.0\nuvicorn==0.27.0\npydantic==2.6.0\npython-dotenv==1.0.1\nsqlalchemy==2.0.25\npasslib[bcrypt]==1.7.4\npython-jose[cryptography]==3.3.0" })
        files.append({ "path": "apps/api/main.py", "content": "from fastapi import FastAPI\nfrom fastapi.middleware.cors import CORSMiddleware\napp = FastAPI()\napp.add_middleware(CORSMiddleware, allow_origins=['*'], allow_methods=['*'])\n@app.get('/health')\ndef health(): return {'status': 'ok'}\nif __name__ == '__main__': import uvicorn; uvicorn.run(app, port=4000)" })
        files.append({ "path": "run_dev.bat", "content": "@echo off\nstart cmd /k \"cd apps\\api && python -m venv venv && venv\\Scripts\\activate && pip install -r requirements.txt && uvicorn main:app --reload --port 4000\"\nstart cmd /k \"cd apps\\web && npm install && npm run dev\"" })
        files.append({ "path": "run_dev.sh", "content": "#!/bin/bash\n(cd apps/api && python3 -m venv venv && source venv/bin/activate && pip install -r requirements.txt && uvicorn main:app --reload --port 4000) &\n(cd apps/web && npm install && npm run dev)" })
        
        return {
            "projectId": project_id,
            "files": files,
            "stats": { "fileCount": len(files), "totalLines": sum([len(f["content"].splitlines()) for f in files]) }
        }
