import json
import re
from typing import Dict, Any, List
from .project_manager import ProjectManager, ARTIFACTS_DIR
from .llm_service import LLMService
from .ai_prompts import PAGE_CODE_PROMPT

class AIBuilder:
    def __init__(self):
        self.project_manager = ProjectManager()
        self.llm = LLMService()

    def _clean_code(self, raw: str) -> str:
        """Strip markdown code blocks"""
        code = raw.strip()
        if code.startswith('```'):
            parts = code.split('\n', 1)
            if len(parts) > 1:
                code = parts[1]
        if code.endswith('```'):
            code = code.rsplit('\n', 1)[0]
        # Remove language identifier if present
        if code.startswith('tsx') or code.startswith('typescript') or code.startswith('javascript'):
            code = code.split('\n', 1)[1]
        return code

    async def build_project(self, project_id: str, description: str) -> Dict[str, Any]:
        docs = await self.project_manager.get_docs(project_id)
        
        # Find Functional and UI/UX docs
        functional_doc = next((d for d in docs if d.category == 'REQUIREMENTS'), None)
        uiux_doc = next((d for d in docs if d.category == 'UI_UX'), None)
        
        # Extract features
        features = []
        if functional_doc:
            matches = re.findall(r'- \*\*(.*?)\*\*', functional_doc.content)
            if matches:
                features = [m.replace('- **', '').replace('**', '') for m in matches]

        # Extract screens
        screens = []
        if uiux_doc:
            matches = re.findall(r'### (.*?) Screen', uiux_doc.content)
            if matches:
                screens = [m.replace('### ', '').replace(' Screen', '') for m in matches]

        files = []

        # 1. Root Configuration
        short_name = description.lower().split(' ')[:3]
        short_name = '-'.join(short_name)
        short_name = re.sub(r'[^a-z0-9-]', '', short_name)[:30]

        files.append({
            "path": "package.json",
            "content": json.dumps({
                "name": short_name,
                "version": "1.0.0",
                "private": True,
                "workspaces": ["apps/*"],
                "scripts": {
                    "dev": "turbo run dev",
                    "build": "turbo run build",
                    "lint": "turbo run lint",
                    "format": "prettier --write \"**/*.{ts,tsx,md}\"",
                    "dev:web": "npm run dev --workspace=web",
                    "dev:api": "npm run dev --workspace=api"
                },
                "devDependencies": {
                    "turbo": "^1.12.4",
                    "prettier": "^3.2.5",
                    "typescript": "^5.3.3"
                }
            }, indent=2)
        })

        files.append({
            "path": "turbo.json",
            "content": json.dumps({
                "$schema": "https://turbo.build/schema.json",
                "globalDependencies": ["**/.env.*local"],
                "pipeline": {
                    "build": {
                        "dependsOn": ["^build"],
                        "outputs": [".next/**", "dist/**"]
                    },
                    "lint": {},
                    "dev": {
                        "cache": False,
                        "persistent": True
                    }
                }
            }, indent=2)
        })

        files.append({
            "path": "tsconfig.json",
            "content": json.dumps({
                "compilerOptions": {
                    "target": "ESNext",
                    "lib": ["dom", "dom.iterable", "esnext"],
                    "allowJs": True,
                    "skipLibCheck": True,
                    "strict": True,
                    "forceConsistentCasingInFileNames": True,
                    "noEmit": True,
                    "esModuleInterop": True,
                    "module": "esnext",
                    "moduleResolution": "node",
                    "resolveJsonModule": True,
                    "isolatedModules": True,
                    "jsx": "preserve",
                    "incremental": True,
                    "baseUrl": ".",
                    "paths": {
                        "@/*": ["./*"]
                    }
                },
                "exclude": ["node_modules"]
            }, indent=2)
        })
        
        # README (Placeholder, updated later?)
        readme_content = f"""# {description}
Automatically generated by **Idea-to-Deploy Platform**.
"""
        files.append({
            "path": "README.md",
            "content": readme_content
        })
        
        files.append({ "path": ".env.example", "content": 'DATABASE_URL="postgresql://user:pass@localhost:5432/db"\nJWT_SECRET="generate-a-secure-secret-here"\nPORT=4000' })

        # 2. Frontend (Next.js + Tailwind)
        files.append({
            "path": "apps/web/package.json",
            "content": json.dumps({
                "name": "web",
                "version": "1.0.0",
                "scripts": {
                    "dev": "next dev",
                    "build": "next build",
                    "start": "next start",
                    "lint": "next lint"
                },
                "dependencies": {
                    "next": "14.2.22",
                    "react": "^18.2.0",
                    "react-dom": "^18.2.0",
                    "lucide-react": "^0.344.0",
                    "clsx": "^2.1.0",
                    "tailwind-merge": "^2.2.1"
                },
                "devDependencies": {
                    "autoprefixer": "^10.4.17",
                    "postcss": "^8.4.35",
                    "tailwindcss": "^3.4.1",
                    "typescript": "^5.3.3",
                    "@types/node": "^20.11.20",
                    "@types/react": "^18.2.57",
                    "@types/react-dom": "^18.2.19"
                }
            }, indent=2)
        })

        files.append({
            "path": "apps/web/tailwind.config.js",
            "content": """module.exports = {
  content: [
    "./app/**/*.{js,ts,tsx,jsx}",
    "./components/**/*.{js,ts,tsx,jsx}",
  ],
  theme: {
    extend: {},
  },
  plugins: [],
}"""
        })
        
        files.append({
            "path": "apps/web/next.config.js",
            "content": "/** @type {import('next').NextConfig} */\nconst nextConfig = { reactStrictMode: true }\nmodule.exports = nextConfig"
        })
        
        files.append({
            "path": "apps/web/postcss.config.js",
            "content": "module.exports = { plugins: { tailwindcss: {}, autoprefixer: {} } }"
        })
        
        files.append({
            "path": "apps/web/app/globals.css",
            "content": """@tailwind base;
@tailwind components;
@tailwind utilities;

:root {
  --foreground-rgb: 0, 0, 0;
  --background-rgb: 255, 255, 255;
}

body {
  color: rgb(var(--foreground-rgb));
  background: rgb(var(--background-rgb));
  min-height: 100vh;
}"""
        })
        
        files.append({
            "path": "apps/web/tsconfig.json",
            "content": json.dumps({
                "compilerOptions": {
                    "target": "ESNext",
                    "lib": ["dom", "dom.iterable", "esnext"],
                    "allowJs": True,
                    "skipLibCheck": True,
                    "strict": True,
                    "noEmit": True,
                    "esModuleInterop": True,
                    "module": "esnext",
                    "moduleResolution": "node",
                    "resolveJsonModule": True,
                    "isolatedModules": True,
                    "jsx": "preserve",
                    "incremental": True,
                    "plugins": [{"name": "next"}],
                    "paths": { "@/*": ["./*"] }
                },
                "include": ["next-env.d.ts", "**/*.ts", "**/*.tsx", ".next/types/**/*.ts"],
                "exclude": ["node_modules"]
            }, indent=2)
        })
        
        files.append({
            "path": "apps/web/next-env.d.ts",
            "content": '/// <reference types="next" />\\n/// <reference types="next/navigation-types/navigation" />\\n'
        })
        
        files.append({
            "path": "apps/web/app/layout.tsx",
            "content": """
import './globals.css';
import { Inter } from 'next/font/google';
import { AuthProvider } from '../context/AuthContext';

const inter = Inter({ subsets: ['latin'] });

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AuthProvider>
            {children}
        </AuthProvider>
      </body>
    </html>
  );
}
"""
        })

        # Auth Utils
        files.append({
            "path": "apps/web/context/AuthContext.tsx", 
            "content": """
'use client';
import React, { createContext, useContext, useState, useEffect } from 'react';
import { useRouter, usePathname } from 'next/navigation';

interface User { id: number; email: string; name: string; }
interface AuthContextType { user: User | null; login: (token: string) => void; logout: () => void; isLoading: boolean; }

const AuthContext = createContext<AuthContextType>({ user: null, login: () => {}, logout: () => {}, isLoading: true });
export const useAuth = () => useContext(AuthContext);

export const AuthProvider = ({ children }: { children: React.ReactNode }) => {
    const [user, setUser] = useState<User | null>(null);
    const [isLoading, setIsLoading] = useState(true);
    const router = useRouter();
    const pathname = usePathname();

    useEffect(() => {
        const token = localStorage.getItem('token');
        if (token) {
            fetch('http://localhost:4000/auth/me', { headers: { 'Authorization': `Bearer ${token}` } })
            .then(res => res.ok ? res.json() : null)
            .then(userData => { if (userData) setUser(userData); else logout(); })
            .catch(() => logout())
            .finally(() => setIsLoading(false));
        } else { setIsLoading(false); }
    }, []);

    const login = (token: string) => {
        localStorage.setItem('token', token);
        fetch('http://localhost:4000/auth/me', { headers: { 'Authorization': `Bearer ${token}` } })
        .then(res => res.json())
        .then(userData => { setUser(userData); router.push('/dashboard'); });
    };

    const logout = () => { localStorage.removeItem('token'); setUser(null); router.push('/login'); };

    useEffect(() => {
        if (!isLoading) {
            const publicRoutes = ['/', '/login', '/register'];
            if (!user && !publicRoutes.includes(pathname)) { router.push('/login'); }
            if (user && (pathname === '/login' || pathname === '/register')) { router.push('/dashboard'); }
        }
    }, [user, isLoading, pathname]);

    return ( <AuthContext.Provider value={{ user, login, logout, isLoading }}> {children} </AuthContext.Provider> );
};
"""
        })

        # --- DYNAMIC UI GENERATION ENGINE ---

        # 1. Inject Reusable Component Library (Using @ alias in fallback)
        files.append({
            "path": "apps/web/components/UIComponents.tsx",
            "content": """
import React from 'react';
import { ArrowRight, CheckCircle, Star, Shield, Zap, Menu, Bell, Settings, User, LogOut, Layout, PieChart } from 'lucide-react';
import { useAuth } from '../context/AuthContext';

// Base Components
export const Button = ({ children, variant = 'primary', className = '', ...props }: any) => {
  const base = "px-4 py-2 rounded font-medium transition-colors flex items-center justify-center gap-2";
  const variants = {
    primary: "bg-blue-600 text-white hover:bg-blue-700",
    secondary: "bg-gray-200 text-gray-800 hover:bg-gray-300",
    neutral: "bg-gray-100 text-gray-900 border border-gray-200",
    outline: "border border-blue-600 text-blue-600 hover:bg-blue-50",
    ghost: "text-gray-600 hover:bg-gray-100"
  };
  return <button className={`${base} ${variants[variant] || variants.primary} ${className}`} {...props}>{children}</button>;
};

export const Input = ({ label, ...props }: any) => (
  <div className="mb-4">
    {label && <label className="block text-sm font-medium mb-1">{label}</label>}
    <input className="w-full px-3 py-2 border rounded outline-none focus:ring-1 focus:ring-blue-600" {...props} />
  </div>
);

// Sections (Simplified)
export const Header = ({ label }: any) => (
    <nav className="border-b px-6 py-4 mb-8 flex items-center justify-between">
        <div className="font-bold text-xl">{label}</div>
        <div className="flex items-center gap-4">
             <Button variant="ghost"><Bell className="w-5 h-5" /></Button>
        </div>
    </nav>
);

export const Hero = ({ label, content, subtext }: any) => (
    <section className="py-12 px-4 text-center">
        <div className="text-blue-600 text-xs font-bold uppercase mb-4">{label}</div>
        <h1 className="text-4xl font-bold mb-4">{content}</h1>
        <p className="text-gray-600 mb-8">{subtext}</p>
        <div className="flex justify-center gap-4">
            <Button>{subtext}</Button>
            <Button variant="secondary">Learn More</Button>
        </div>
    </section>
);

export const AuthCard = ({ label }: any) => {
    const { login } = useAuth();
    return (
        <div className="max-w-md mx-auto border p-8 rounded-lg shadow-sm">
            <h2 className="text-2xl font-bold mb-4 text-center">{label}</h2>
             <div className="space-y-4">
                <Input label="Email" placeholder="email@example.com" />
                <Input label="Password" type="password" />
                <Button className="w-full" onClick={() => login('token')}>{label}</Button>
             </div>
        </div>
    );
};

export const Sidebar = ({ label }: any) => (
    <div className="hidden lg:flex flex-col w-64 fixed left-0 top-0 bottom-0 bg-gray-100 border-r p-6">
        <div className="text-xl font-bold mb-10 tracking-tight">{label}</div>
        <div className="space-y-2 flex-1">
             <Button variant="ghost" className="w-full justify-start">Dashboard</Button>
             <Button variant="ghost" className="w-full justify-start">Settings</Button>
        </div>
        <Button variant="ghost" className="w-full justify-start text-red-600">Logout</Button>
    </div>
);

export const Footer = ({ label }: any) => (
    <footer className="border-t py-8 text-center text-gray-500 text-sm">
        © 2024 idea-to-deploy.
    </footer>
);
"""
        })
        
        # 2. Dynamic Component & Page Builder
        wireframes_path = ARTIFACTS_DIR / project_id / "docs" / "wireframes.json"
        
        design_specs = {}
        if wireframes_path.exists():
            with open(wireframes_path, 'r', encoding='utf-8') as f:
                wf_data = json.loads(f.read())
                for wf in wf_data.get('wireframes', []):
                    key = wf.get('screenKey') or wf.get('screen', '').lower().replace(' ', '')
                    design_specs[key.lower()] = wf
        
        defined_screens = list(design_specs.keys())
        normalized_screens = list(set([s.lower().replace(' ', '') for s in screens] + defined_screens))
        
        
        generated_slugs = []
        
        # Generate Pages List
        for screen_key in normalized_screens:
            is_root = False
            slug = screen_key
            if 'dashboard' in screen_key or 'home' in screen_key or 'landing' in screen_key:
                 if 'dashboard' in screen_key: is_root = True 
            layout = design_specs.get(screen_key, {}).get('layout', [])
            
            wf_layout_str = json.dumps(design_specs.get(screen_key, {}), indent=2)
            raw = await self.llm.generate_content('PAGE_CODE', {
                "idea": description,
                "screen_name": screen_key,
                "wireframe": wf_layout_str
            }, PAGE_CODE_PROMPT)
            content = self._clean_code(raw)
            
            # Determine Path
            path_slug = '' if is_root else screen_key
            if path_slug == 'dashboard': path_slug = ''
            
            if path_slug == '': path = "apps/web/app/page.tsx"
            else: path = f"apps/web/app/{path_slug}/page.tsx"
            
            files.append({ "path": path, "content": content })
            generated_slugs.append(path_slug)
            

        # 3. Backend (Simple Keep)
        files.append({
            "path": "apps/api/package.json",
            "content": json.dumps({ "name": "api", "version": "1.0.0", "scripts": { "dev": "uvicorn main:app --reload --port 4000", "start": "uvicorn main:app --port 4000" } }, indent=2)
        })
        files.append({ "path": "apps/api/requirements.txt", "content": "fastapi==0.109.0\nuvicorn==0.27.0\npydantic==2.6.0\npython-dotenv==1.0.1\nsqlalchemy==2.0.25\npasslib[bcrypt]==1.7.4\npython-jose[cryptography]==3.3.0" })
        files.append({ "path": "apps/api/main.py", "content": "from fastapi import FastAPI\nfrom fastapi.middleware.cors import CORSMiddleware\napp = FastAPI()\napp.add_middleware(CORSMiddleware, allow_origins=['*'], allow_methods=['*'])\n@app.get('/health')\ndef health(): return {'status': 'ok'}\nif __name__ == '__main__': import uvicorn; uvicorn.run(app, port=4000)" })
        files.append({ "path": "run_dev.bat", "content": "@echo off\nstart cmd /k \"cd apps\\api && python -m venv venv && venv\\Scripts\\activate && pip install -r requirements.txt && uvicorn main:app --reload --port 4000\"\nstart cmd /k \"cd apps\\web && npm install && npm run dev\"" })
        files.append({ "path": "run_dev.sh", "content": "#!/bin/bash\n(cd apps/api && python3 -m venv venv && source venv/bin/activate && pip install -r requirements.txt && uvicorn main:app --reload --port 4000) &\n(cd apps/web && npm install && npm run dev)" })
        
        return {
            "projectId": project_id,
            "files": files,
            "stats": { "fileCount": len(files), "totalLines": sum([len(f["content"].splitlines()) for f in files]) }
        }
    