import type { Metadata } from 'next'
import './globals.css'

export const metadata: Metadata = {
  title: 'Build an event management platform that allows org...',
  description: 'Generated by Idea-to-Deploy',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className="min-h-screen bg-background antialiased">
        {children}
      </body>
    </html>
  )
}
